menus:
	- 
		name: Home
		link: /
	- 
		name: Archive
		link: archives/
	- 
		name: About
		link: about/

profile:
	location: Cluj-Napoca, Romania
	github: calindotgabriel
	#stackoverflow: 
		#title: yumemor
		#href: http://stackoverflow.com/users/5662132/yumemor
	#organization: 组织/公司

github: 
	username: calindotgabriel
  popular_repos: [hexo-theme-primer]

#comment:
	#duoshuo_username: 
	#disqus_username: 

search: local #google｜local
